import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ExportRecord } from "@shared/schema";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Download, History, Plus } from "lucide-react";
import { formatDateTime } from "@/lib/utils";
import { useToast } from "@/hooks/use-toast";

type ExportRecordWithUserName = ExportRecord & { userName: string };

export function RecentExports() {
  const { toast } = useToast();
  const { data: exports = [], isLoading } = useQuery<ExportRecordWithUserName[]>({
    queryKey: ["/api/export-records"],
  });

  const handleDownload = (exportRecord: ExportRecordWithUserName) => {
    toast({
      title: "Download requested",
      description: "The export is being generated and will download shortly.",
    });
    
    // This would need to be updated with actual download functionality
    // For now, we'll just simulate a download
    setTimeout(() => {
      toast({
        title: "Download complete",
        description: `${exportRecord.reportName} has been downloaded.`,
      });
    }, 2000);
  };

  if (isLoading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Recent Exports</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="animate-pulse space-y-4">
            {[...Array(5)].map((_, i) => (
              <div key={i} className="h-12 bg-neutral-200 rounded"></div>
            ))}
          </div>
        </CardContent>
      </Card>
    );
  }

  const getFileIcon = (format: string) => {
    switch (format.toLowerCase()) {
      case "xlsx":
        return <span className="text-green-600 mr-2">📊</span>;
      case "csv":
        return <span className="text-indigo-600 mr-2">📈</span>;
      case "pdf":
        return <span className="text-red-600 mr-2">📄</span>;
      default:
        return <span className="text-neutral-600 mr-2">📑</span>;
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Recent Exports</CardTitle>
      </CardHeader>
      <CardContent>
        <table className="w-full">
          <thead>
            <tr className="border-b border-neutral-200">
              <th className="text-left py-3 px-4 text-sm font-medium text-neutral-700">Report</th>
              <th className="text-left py-3 px-4 text-sm font-medium text-neutral-700">Date</th>
              <th className="text-left py-3 px-4 text-sm font-medium text-neutral-700">Company</th>
              <th className="text-left py-3 px-4 text-sm font-medium text-neutral-700">Generated By</th>
              <th className="text-left py-3 px-4 text-sm font-medium text-neutral-700">Actions</th>
            </tr>
          </thead>
          <tbody>
            {exports.length === 0 ? (
              <tr>
                <td colSpan={5} className="py-4 text-center text-neutral-500">
                  No recent exports found
                </td>
              </tr>
            ) : (
              exports.map((exportRecord) => (
                <tr key={exportRecord.id} className="border-b border-neutral-200">
                  <td className="py-3 px-4">
                    <div className="flex items-center">
                      {getFileIcon(exportRecord.format || "xlsx")}
                      <span>{exportRecord.reportName}</span>
                    </div>
                  </td>
                  <td className="py-3 px-4">{formatDateTime(exportRecord.createdAt)}</td>
                  <td className="py-3 px-4">{exportRecord.company || "All Companies"}</td>
                  <td className="py-3 px-4">{exportRecord.userName}</td>
                  <td className="py-3 px-4">
                    <div className="flex space-x-2">
                      <Button 
                        size="icon" 
                        variant="ghost" 
                        onClick={() => handleDownload(exportRecord)}
                      >
                        <Download className="h-4 w-4 text-primary" />
                      </Button>
                      <Button size="icon" variant="ghost">
                        <History className="h-4 w-4 text-neutral-500" />
                      </Button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </CardContent>
    </Card>
  );
}

export function ScheduledReports() {
  const [reports] = useState([
    {
      id: 1,
      name: "Monthly Payroll Export - Butters",
      frequency: "Monthly (30th)",
      recipients: "admin@hitec.com, payroll@external.com",
      nextRun: "2023-10-30",
      status: "Active",
    },
    {
      id: 2,
      name: "Monthly Payroll Export - Makana",
      frequency: "Monthly (30th)",
      recipients: "admin@hitec.com, payroll@external.com",
      nextRun: "2023-10-30",
      status: "Active",
    },
    {
      id: 3,
      name: "Weekly Overtime Summary",
      frequency: "Weekly (Friday)",
      recipients: "admin@hitec.com, hr@hitec.com",
      nextRun: "2023-10-13",
      status: "Paused",
    },
  ]);

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle>Scheduled Reports</CardTitle>
        <Button>
          <Plus className="h-4 w-4 mr-2" />
          Schedule New Report
        </Button>
      </CardHeader>
      <CardContent>
        <table className="w-full">
          <thead>
            <tr className="border-b border-neutral-200">
              <th className="text-left py-3 px-4 text-sm font-medium text-neutral-700">Report Name</th>
              <th className="text-left py-3 px-4 text-sm font-medium text-neutral-700">Frequency</th>
              <th className="text-left py-3 px-4 text-sm font-medium text-neutral-700">Recipients</th>
              <th className="text-left py-3 px-4 text-sm font-medium text-neutral-700">Next Run</th>
              <th className="text-left py-3 px-4 text-sm font-medium text-neutral-700">Status</th>
              <th className="text-left py-3 px-4 text-sm font-medium text-neutral-700">Actions</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((report) => (
              <tr key={report.id} className="border-b border-neutral-200">
                <td className="py-3 px-4">{report.name}</td>
                <td className="py-3 px-4">{report.frequency}</td>
                <td className="py-3 px-4">{report.recipients}</td>
                <td className="py-3 px-4">{report.nextRun}</td>
                <td className="py-3 px-4">
                  <div className={`px-2 py-1 rounded-full text-xs font-medium inline-block ${
                    report.status === "Active" 
                      ? "bg-green-100 text-green-800" 
                      : "bg-red-100 text-red-800"
                  }`}>
                    {report.status}
                  </div>
                </td>
                <td className="py-3 px-4">
                  <div className="flex space-x-2">
                    <Button size="icon" variant="ghost">
                      <Edit className="h-4 w-4 text-primary" />
                    </Button>
                    {report.status === "Active" ? (
                      <Button size="icon" variant="ghost">
                        <Pause className="h-4 w-4 text-red-500" />
                      </Button>
                    ) : (
                      <Button size="icon" variant="ghost">
                        <Play className="h-4 w-4 text-green-500" />
                      </Button>
                    )}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </CardContent>
    </Card>
  );
}

// Import needed icons for the component
import { Edit, Pause, Play } from "lucide-react";
